language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- 3.9-dev
before_install:
- pip install "pytest>=3.6"
- pip install pytest-cov
- pip install coveralls
script:
- pytest
after_success:
- coveralls
deploy:
  provider: pypi
  user: sigvaldm
  on:
    tags: true
    python: 3.8
  password:
    secure: gtEiupsJx1dU3oNQZFYJPZdNr0Bz5JtdEPWQakKB0HML7f3Ql8yiX77dB2HcQv9fnbJdKha4KLCeznWPKpgAv85bbW3iJDXx5jRNhA9eUeM9KFoQiFCRYetcRoRJxVQvuJGnTr3nj11QJTm7XelfjmPP98Ht5rvk88S9PDh1WdBk97S+IP7DX4YjH3OeFU44LSzwBSSoKoX2z/t0pRA377BAl9g8+HLRMnp8cz5NbN63fbgjCHuFZnvve/+72yyUooSEIfvtTgjifYQs3aExalS4iRDWndQiWCrEq/Rh5VXflrSpdBnSN9eeb5xEyx/m0ygrw3pFIHnnM5HZU67GvWXT5ErQRfpE8BdggFKuvzanx13Jkz62AsPVjZMAIUjG2KipSaP633p5S+b0JVF4yUa/kcelVcSm9HfzrCH0VHdDf4uwkhPM7P3kd4GGvqEdF3s40EfgoBxqFZ7sNhEAbWh3kDM1eigg+kpMQRbK6Yt5PLfUBQemBjiStxhpIbccCVvXRKkCpSXsUvpsAAwXQpvSI41bFRjeaSnTm/iyiHjxHiUrVMlJqn07zDtnwa6odpRAcuZAgJbkGqUp96upc721qcIuVYr+xb9Vv0pSstqArc+7lbBB1yKFK74tPT+razlwCvacnH69Y5Th1y+UdmMilKMVB+VlcNTdRy92r/8=
